spring:
  main:
    web-application-type: none

  application:
    ui:
      title: Dalek Game

game:
  map:
    strategy: BOUNDED
    width: 20
    height: 20
  configurationsByDifficulty:
    EASY:
      enemies: 3
      lives: 1
      powerups:
        TELEPORT: 4
        BOMB: 1
        REVERSE_TIME: 3
    NORMAL:
      enemies: 5
      lives: 1
      powerups:
        TELEPORT: 1
        BOMB: 1
        REVERSE_TIME: 2
    HARD:
      enemies: 7
      lives: 1
      powerups:
        TELEPORT: 1
        BOMB: 1
        REVERSE_TIME: 1